IRC_VERSIONS = %w|6.8.0.beta.97.da30a7c 6.8.0.beta.63.67d2581|

IRC_VERSIONS.each do |version|
  appraise "infopark_rails_connector-#{version}" do
    gem "infopark_rails_connector", "#{version}"
    gem "rails", "3.0.19"
    gem 'mysql'
  end
end

appraise "infopark_rails_connector-6.8.0.beta.200.121.856b3bf" do
  gem "infopark_rails_connector", "6.8.0.beta.200.121.856b3bf"
  gem "infopark_fiona_connector", "6.8.0.beta.200.121.856b3bf"
  gem "rails", "3.0.19"
  gem 'mysql'
end

appraise "infopark_rails_connector-6.8.0.beta.200.475.e6438f7" do
  gem "infopark_rails_connector", "6.8.0.beta.200.475.e6438f7"
  gem "infopark_fiona_connector", "6.8.0.beta.200.475.e6438f7"
  gem "rails", "3.1.10"
  gem 'mysql'
end

appraise "infopark_rails_connector-6.8.0.beta.200.165.bf42591" do
  gem "infopark_rails_connector", "6.8.0.beta.200.165.bf42591"
  gem "infopark_fiona_connector", "6.8.0.beta.200.165.bf42591"
  gem "rails", "3.1.10"
  gem 'mysql'
end

appraise "infopark_rails_connector-6.8.0.beta.200.761.8cc6da0" do
  gem "infopark_rails_connector", "6.8.0.beta.200.761.8cc6da0"
  gem "infopark_fiona_connector", "6.8.0.beta.200.761.8cc6da0"
  # Please install the mysql adapter: `gem install activerecord-mysql-adapter` (can't activate mysql (~> 2.8.1), already activated mysql-2.9.0. Make sure all dependencies are added to Gemfile.)
  gem "mysql", "~> 2.8.1"
  gem "rails", "3.2.11"
end

appraise "infopark_rails_connector-6.8.0.539.93842523" do
  gem 'infopark_rails_connector', '6.8.0.539.93842523'
  gem 'infopark_fiona_connector', '6.8.0.539.93842523'
  gem "mysql", "~> 2.8.1"
  gem 'rails', '3.2.12'
end

appraise "infopark_rails_connector-6.8.3.174.51542603" do
  gem 'infopark_rails_connector', '6.8.3.174.51542603'
  gem 'infopark_fiona_connector', '6.8.3.174.51542603'
  gem 'mysql2'
  gem 'rails', '3.2.12'
end
