source "https://rubygems.org"
gem "infopark_reactor", :path=>"../infopark_reactor"
gem "rspec-rails", "~> 2.0"
gem "infopark_fiona_connector", '6.10.0.beta1'
gem "mysql2"
gem "nokogiri", "< 1.6.0"
gem "rails", "4.1.6"
