# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'rake/dsl_definition'
require File.expand_path('../config/application', __FILE__)
require 'rake'

# fix for NoMethodError: undefined method `last_comment'
# last_comment was removed in rake 12
module FixForRakeLastComment
  def last_comment
    last_description
  end 
end
Rake::Application.__send__ :include, FixForRakeLastComment

ReactorTest::Application.load_tasks
